global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['host.docker.internal:9090']  # Prometheus selbst auf Port 9090

  - job_name: 'Playground_AspNetElastic'
    static_configs:
      - targets: ['host.docker.internal:7123']
    scheme: http                     # Hier fügst du das scheme für den Job hinzu
    metrics_path: '/metrics-text'