# Module: http
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/8.10/metricbeat-module-http.html

- module: http
  enabled: false
  metricsets:
    - json
  period: 15s
  hosts: ["localhost:5000"]
  namespace: "json_frontend"
  path: "/metrics"
  #body: ""
  #method: "GET"
  #username: "user"
  #password: "secret"
  #request.enabled: false
  #response.enabled: false
  #json.is_array: false
  #dedot.enabled: false

#- module: http
  #metricsets:
  #  - server
  #host: "localhost"
  #port: "5000"
  #enabled: true
  #paths:
  #  - path: "/foo"
  #    namespace: "foo"
  #    fields: # added to the the response in root. overwrites existing fields
  #      key: "value"